### ISSUE TITLE
Make input fields smaller

### ISSUE THREAD

**Issue by RaitaroH** [style-it-themes/discord-inspired-bits-dark#5]
The input field in chat is just too tall.

```
.textArea-2Spzkt {
    height: 35px !important;
    padding-bottom: 0px !important;
}
```

Maybe add this too:
```
.channelTextArea-rNsIhG {
    margin-bottom: 15px !important;
    padding-top: 15px !important;
}
```

**Comment by the-j0k3r** [comment]
Thanks.

Assuming that the multiline is unbroken and some testing (since this input has a default auto height) then as discussed we can go ahead and add this.

 I gave some thought to what you said, so I don't mind making this a default rather than optional since you're applying it against pepermint ICE also if I understood correctly?

**Comment by RaitaroH** [comment]
Yes, that's correct.
